# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/CreateAccount.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 919)
        MainWindow.setStyleSheet("background-image:url(\"../IMG/Background.png\");")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 0, 231, 221))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setStyleSheet("z-index:1;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/images__1_-removebg-preview.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(230, 580, 261, 71))
        self.btn_register.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"background:rgb(255, 255, 255);\n"
"border-radius:32;\n"
"color: black;")
        self.btn_register.setObjectName("btn_register")
        self.txt_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(100, 320, 511, 51))
        self.txt_email.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_email.setInputMask("")
        self.txt_email.setText("")
        self.txt_email.setObjectName("txt_email")
        self.txt_fullname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_fullname.setGeometry(QtCore.QRect(100, 380, 511, 51))
        self.txt_fullname.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_fullname.setInputMask("")
        self.txt_fullname.setText("")
        self.txt_fullname.setObjectName("txt_fullname")
        self.txt_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(100, 440, 511, 51))
        self.txt_password.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_password.setInputMask("")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(110, 700, 491, 51))
        self.btn_login.setStyleSheet("font: 25pt \"white\";\n"
"background:rgb(255, 255, 255);\n"
"border-radius:32;\n"
"color: black;")
        self.btn_login.setObjectName("btn_login")
        self.txt_conf_pwd = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_conf_pwd.setGeometry(QtCore.QRect(100, 500, 511, 51))
        self.txt_conf_pwd.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_conf_pwd.setInputMask("")
        self.txt_conf_pwd.setText("")
        self.txt_conf_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_conf_pwd.setObjectName("txt_conf_pwd")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-730, -110, 1421, 1041))
        self.label.setStyleSheet("background:rgb(24, 24, 24);\n"
"border-radius:25")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../../../../../Downloads/hinh-nen-may-tinh-chill-4k31.jpg"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 631, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white ;  /* Chỉnh màu chữ thành màu đỏ\n"
" */\n"
"};\n"
"font: 700 italic 40pt \"Segoe UI\";\n"
"z-index:2\n"
"")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 330, 31, 21))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/envelope-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 390, 31, 21))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/person-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.btn_lock1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_lock1.setGeometry(QtCore.QRect(560, 450, 31, 21))
        self.btn_lock1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_lock1.setIcon(icon2)
        self.btn_lock1.setObjectName("btn_lock1")
        self.btn_lock2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_lock2.setGeometry(QtCore.QRect(560, 520, 31, 21))
        self.btn_lock2.setText("")
        self.btn_lock2.setIcon(icon2)
        self.btn_lock2.setObjectName("btn_lock2")
        self.label.raise_()
        self.btn_login.raise_()
        self.txt_password.raise_()
        self.btn_register.raise_()
        self.txt_email.raise_()
        self.label_2.raise_()
        self.txt_conf_pwd.raise_()
        self.txt_fullname.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.btn_lock1.raise_()
        self.btn_lock2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_register.setText(_translate("MainWindow", "Sign Up"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.txt_fullname.setPlaceholderText(_translate("MainWindow", "Username"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btn_login.setText(_translate("MainWindow", "Already have an account?"))
        self.txt_conf_pwd.setPlaceholderText(_translate("MainWindow", "Comfirm Password"))
        self.label_3.setText(_translate("MainWindow", "Đăng ký vào spotify"))
