# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(693, 892)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(-760, -10, 1461, 941))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/hinh-nen-may-tinh-chill-4k31.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 231, 221))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setStyleSheet("z-index:1;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/images__1_-removebg-preview.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txt_email_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_email_2.setGeometry(QtCore.QRect(90, 380, 541, 51))
        self.txt_email_2.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_email_2.setInputMask("")
        self.txt_email_2.setText("")
        self.txt_email_2.setObjectName("txt_email_2")
        self.txt_oldpassword = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_oldpassword.setGeometry(QtCore.QRect(90, 450, 541, 51))
        self.txt_oldpassword.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_oldpassword.setInputMask("")
        self.txt_oldpassword.setText("")
        self.txt_oldpassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_oldpassword.setObjectName("txt_oldpassword")
        self.txt_newpassword = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_newpassword.setGeometry(QtCore.QRect(90, 520, 541, 51))
        self.txt_newpassword.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_newpassword.setInputMask("")
        self.txt_newpassword.setText("")
        self.txt_newpassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_newpassword.setObjectName("txt_newpassword")
        self.txt_email_3 = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_email_3.setGeometry(QtCore.QRect(220, 600, 291, 61))
        self.txt_email_3.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_email_3.setInputMask("")
        self.txt_email_3.setText("")
        self.txt_email_3.setObjectName("txt_email_3")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 230, 631, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white ;  /* Chỉnh màu chữ thành màu đỏ\n"
" */\n"
"};\n"
"font: 700 italic 40pt \"Segoe UI\";\n"
"z-index:2\n"
"")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(590, 390, 31, 21))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/envelope-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 540, 31, 21))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/lock-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 460, 31, 21))
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.btn_login_2 = QtWidgets.QPushButton(parent=Dialog)
        self.btn_login_2.setGeometry(QtCore.QRect(180, 680, 371, 71))
        self.btn_login_2.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"background:rgb(255, 255, 255);\n"
"border-radius:32;\n"
"")
        self.btn_login_2.setObjectName("btn_login_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.txt_email_2.setPlaceholderText(_translate("Dialog", "Email"))
        self.txt_oldpassword.setPlaceholderText(_translate("Dialog", "Old password"))
        self.txt_newpassword.setPlaceholderText(_translate("Dialog", "New Password"))
        self.txt_email_3.setPlaceholderText(_translate("Dialog", "    Done"))
        self.label_3.setText(_translate("Dialog", "đổi mật khẩu"))
        self.btn_login_2.setText(_translate("Dialog", "register"))
