# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/Login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 919)
        MainWindow.setStyleSheet("background-image:url(\"../IMG/Background.png\");")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(240, 520, 221, 71))
        self.btn_login.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"background:rgb(255, 255, 255);\n"
"border-radius:32;\n"
"color: black;")
        self.btn_login.setObjectName("btn_login")
        self.txt_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(70, 360, 541, 51))
        self.txt_email.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_email.setInputMask("")
        self.txt_email.setText("")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(70, 430, 541, 51))
        self.txt_password.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"border-radius:10")
        self.txt_password.setInputMask("")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-750, -40, 1421, 891))
        self.label.setStyleSheet("background:rgb(24, 24, 24);\n"
"border-radius:25")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/hinh-nen-may-tinh-chill-4k31.jpg"))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 370, 31, 21))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/envelope-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 231, 221))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setStyleSheet("z-index:1;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/images__1_-removebg-preview.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 631, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white ;  /* Chỉnh màu chữ thành màu đỏ\n"
" */\n"
"};\n"
"font: 700 italic 40pt \"Segoe UI\";\n"
"z-index:2\n"
"")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_lock = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_lock.setGeometry(QtCore.QRect(560, 450, 31, 21))
        self.btn_lock.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_lock.setIcon(icon1)
        self.btn_lock.setObjectName("btn_lock")
        self.btn_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(150, 660, 371, 71))
        self.btn_register.setStyleSheet("font: 32pt \"Pinky Blues\";\n"
"background:rgb(255, 255, 255);\n"
"border-radius:32;\n"
"color: black;\n"
"\n"
"")
        self.btn_register.setObjectName("btn_register")
        self.label.raise_()
        self.txt_password.raise_()
        self.btn_login.raise_()
        self.txt_email.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.btn_lock.raise_()
        self.btn_register.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Đăng nhập vào spotify"))
        self.btn_register.setText(_translate("MainWindow", "register"))
