# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_GiaNghia_ThienBao/ui/songItems.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 180)
        Form.setStyleSheet("background-color: #2e2e2e; /* Dark gray for the background */\n"
"    border: 2px solid #444444; /* Slightly lighter gray for the border */\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3); /* Subtle shadow for depth */")
        self.lbl_name = QtWidgets.QLabel(parent=Form)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 231, 21))
        self.lbl_name.setStyleSheet("color: #dddddd;")
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_artist = QtWidgets.QLabel(parent=Form)
        self.lbl_artist.setGeometry(QtCore.QRect(10, 40, 231, 21))
        self.lbl_artist.setStyleSheet("color: #dddddd;")
        self.lbl_artist.setObjectName("lbl_artist")
        self.lbl_album = QtWidgets.QLabel(parent=Form)
        self.lbl_album.setGeometry(QtCore.QRect(10, 70, 231, 21))
        self.lbl_album.setStyleSheet("color: #dddddd;")
        self.lbl_album.setObjectName("lbl_album")
        self.lbl_playcount = QtWidgets.QLabel(parent=Form)
        self.lbl_playcount.setGeometry(QtCore.QRect(10, 100, 231, 21))
        self.lbl_playcount.setStyleSheet("color: #dddddd;")
        self.lbl_playcount.setObjectName("lbl_playcount")
        self.btn_play = QtWidgets.QPushButton(parent=Form)
        self.btn_play.setGeometry(QtCore.QRect(140, 130, 100, 32))
        self.btn_play.setStyleSheet("    background-color: #4caf50; /* Green button for a clean look */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 15px;\n"
"    margin-top: 5px;")
        self.btn_play.setObjectName("btn_play")
        self.btn_add = QtWidgets.QPushButton(parent=Form)
        self.btn_add.setGeometry(QtCore.QRect(10, 130, 100, 32))
        self.btn_add.setStyleSheet("    background-color: #4caf50; /* Green button for a clean look */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px 15px;\n"
"    margin-top: 5px;")
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_name.setText(_translate("Form", "Name:"))
        self.lbl_artist.setText(_translate("Form", "Artist: "))
        self.lbl_album.setText(_translate("Form", "Album:"))
        self.lbl_playcount.setText(_translate("Form", "Played:"))
        self.btn_play.setText(_translate("Form", "Nghe"))
        self.btn_add.setText(_translate("Form", "Thêm"))
